// common
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_SYSTEM = 'SET_SYSTEM'
export const SET_PAGE = 'SET_PAGE'
export const SET_ELEMENTS = 'SET_ELEMENTS'
export const UPDATE_ELEMENT = 'UPDATE_ELEMENT'
export const TRIGGER_ELEMENT = 'TRIGGER_ELEMENT'

// edit
export const SET_HOVER_ELEMENTS = 'SET_HOVER_ELEMENTS'
export const SET_ACTIVE_ELEMENTS = 'SET_ACTIVE_ELEMENTS'
export const SET_MULTIPLE_ELEMENT = 'SET_MULTIPLE_ELEMENT'
